--CRIA TABELAS BASE
CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE TipoDePet
(
	IdTipo INT PRIMARY KEY IDENTITY,
	Nome CHAR(10) NOT NULL UNIQUE
)

--CRIA TABELAS COMPOSTAS 
CREATE TABLE Raca
(
	 IdRaca INT PRIMARY KEY IDENTITY,
	 IdTipo INT FOREIGN KEY REFERENCES TipoDePet(IdTipo) NOT NULL,
	 Nome CHAR(20) NOT NULL UNIQUE
)

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL,
	Nome CHAR(10) NOT NULL
)

 CREATE TABLE Pets
 (
	IdPet INT PRIMARY KEY IDENTITY,
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca) NOT NULL, 
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario) NOT NULL,
	Dono CHAR(10) NOT NULL,
	Nome CHAR(10) NOT NULL,
	DataDeNascimento DATE NOT NULL
 )

