--DDL

CREATE DATABASE Exercicio_1_4

--CRIADAS TABELAS FORTES 

CREATE TABLE TipoDePermissão
(
	IdTipo INT PRIMARY KEY IDENTITY,
	Nome CHAR(15) NOT NULL 
)

CREATE TABLE Estilo
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Nome CHAR(10) NOT NULL UNIQUE
)

CREATE TABLE Artista
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome CHAR(15) NOT NULL UNIQUE
)

CREATE TABLE Plataforma
(
	IdPlataforma INT PRIMARY KEY IDENTITY,
	Nome CHAR(10) NOT NULL UNIQUE
)

-- CRAIADAS TABELAS FRACAS 

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipo INT FOREIGN KEY REFERENCES TipoDePermissão(IdTipo) NOT NULL,
	IdPlataforma INT FOREIGN KEY REFERENCES Plataforma(IdPlataforma) NOT NULL,
	Nome CHAR(10) NOT NULL,
	Email CHAR(50) NOT NULL UNIQUE 
)

CREATE TABLE PlataformaArtisTa
(
	IdPlataformaArtisTa INT PRIMARY KEY IDENTITY,
	IdPlataforma INT FOREIGN KEY REFERENCES Plataforma(IdPlataforma) NOT NULL,
	IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista) NOT NULL,
)


CREATE TABLE Album
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista) NOT NULL,
	Titulo CHAR(10) NOT NULL UNIQUE,
	DataDeLancamento DATE NOT NULL,
	Localizacao CHAR(30) NOT NULL,
	QuantidadeDeMinutos CHAR(10) NOT NULL
)

CREATE TABLE EstiloAlbum
(
	IdEstiloAlbum INT PRIMARY KEY IDENTITY,
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum) NOT NULL,
	IdEstilo INT FOREIGN KEY REFERENCES Estilo(IdEstilo) NOT NULL
)

CREATE TABLE PlataformaAlbum
(
	IdPlataformaAlbum INT PRIMARY KEY IDENTITY,
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum) NOT NULL,
	IdPlataforma INT FOREIGN KEY REFERENCES Plataforma(IdPlataforma)NOT NULL
)