--DDL

-- CRIA TABELAS SIMPLES (SEM FK)

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(10) NOT NULL UNIQUE
)

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(10) NOT NULL UNIQUE
)

-- CRIA TABELAS COMPOSTAS (COM FK)

CREATE TABLE Modelo 
(
	IdModelo INT PRIMARY KEY IDENTITY,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	Nome VARCHAR(10) NOT NULL
)

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL,
	Placa CHAR(7)
)

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	Nome CHAR(20) NOT NULL,
	Cpf CHAR(11) NOT NULL 
)


SELECT * FROM Empresa
SELECT * FROM Marca
SELECT * FROM Modelo
SELECT * FROM Veiculo
SELECT * FROM Cliente