--DML - DATA MANIPULATION LANGUAGE 

INSERT INTO FUNCIONÁRIOS(Nome)
VALUES('Vagner')

UPDATE FUNCIONÁRIOS
SET Nome = 'Robilson' WHERE Nome = 'Carlos'

DELETE FROM FUNCIONÁRIOS WHERE Nome = 'Vagner'

INSERT INTO EMPRESAS(IdFuncionario,Nome)
VALUES (9,'GOOGLE')